In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/mac/Desktop/DataTeam/SunSystems/LMV/Interface_takaful_1st_Installation/Ready/Encaissement_13-05-2026_17_09_.csv',sep=';')
df.head()

,CodeIFC,NoPolice,NoAdhesion,NomAssure,NomContractant,DateEffet,DateEmission,DateEcheance,DateEnvoi,DateReglement,...,Produit,Support,ChampLettrage,Garantie,CompteTakaful,CritereCompte,Montant,Solde,Group1,Group2
0,ENCADE,12630.0,369443.0,JRIRI,JRIRI,2092024.0,3042026.0,2042026.0,2042026.0,2042026.0,...,401.0,A00,369443.0,G01,CF01,EQADE-PRIME_TTC,86.51,"86,51",G01,369443.0
1,ENCADE,19918.0,366122.0,GORY,GORY,1042026.0,17032026.0,1042026.0,2042026.0,2042026.0,...,400.0,A00,366122.0,G01,CF01,EQADE-PRIME_TTC,165.00,165,G01,366122.0
2,ENCADE,5206.0,367959.0,RABIH,RABIH,1032023.0,3042026.0,1042026.0,2042026.0,2042026.0,...,401.0,A00,367959.0,G01,CF01,EQADE-PRIME_TTC,59.95,"59,95",G01,367959.0
3,ENCADE,16814.0,370784.0,BOUGGAR,BOUGGAR,29122025.0,3042026.0,28032026.0,2042026.0,2042026.0,...,400.0,A00,370784.0,G01,CF01,EQADE-PRIME_TTC,321.75,"321,75",G01,370784.0
4,ENCADE,19408.0,367329.0,MACHACH,MACHACH,1042026.0,30032026.0,1042026.0,2042026.0,2042026.0,...,401.0,A00,367329.0,G01,CF01,EQADE-PRIME_TTC,126.04,"126,04",G01,367329.0

In [12]:
# Avec Pandas
resultat = df.groupby(['Group1', 'Group2'])['Solde'].sum().reset_index()

# Pour l'afficher :
resultat

       Group1      Group2  Solde
0      ENCADE   2042026.0    0.0
1      ENCADE   9042026.0    0.0
2      ENCADE  16042026.0    0.0
3      ENCADE  23042026.0    0.0
4      ENCADE  30042026.0    0.0
...       ...         ...    ...
14484     G07    378606.0    0.0
14485     G07    378610.0    0.0
14486     G07    379119.0    0.0
14487     G07    379122.0    0.0
14488     G07    379123.0    0.0

[14489 rows x 3 columns]

In [18]:
# 1. Nettoyage de la colonne Solde
df['Solde'] = df['Solde'].astype(str).str.replace(',', '.').astype(float)

# 2. Somme avec groupby
resultat = df.groupby(['Group1', 'Group2'])['Solde'].sum().reset_index()

In [19]:
resultat['Solde'].sum()

5.548901615970436e-12