In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Ready/Encaissement_13-05-2026_17_09.csv',sep=';')
df.head()

,CodeIFC,NoPolice,NoAdhesion,NomAssure,NomContractant,DateEffet,DateEmission,DateEcheance,DateEnvoi,DateReglement,...,Produit,Support,ChampLettrage,Garantie,CompteTakaful,CritereCompte,Montant,Solde,Group1,Group2
0,ENCADE,12630.0,369443.0,JRIRI,JRIRI,2092024.0,3042026.0,2042026.0,2042026.0,2042026.0,...,401.0,A00,369443.0,G01,CF01,EQADE-PRIME_TTC,86.51,"86,51",G01,369443.0
1,ENCADE,12630.0,369443.0,JRIRI,JRIRI,2092024.0,3042026.0,2042026.0,2042026.0,2042026.0,...,401.0,A00,369443.0,G01,CF01,EQADE-PRIME_HT,78.65,"-78,65",G01,369443.0
2,ENCADE,12630.0,369443.0,JRIRI,JRIRI,2092024.0,3042026.0,2042026.0,2042026.0,2042026.0,...,401.0,A00,369443.0,G01,CF01,EQADE-TAXE_TSA,7.86,"-7,86",G01,369443.0
3,ENCADE,12630.0,369443.0,JRIRI,JRIRI,2092024.0,3042026.0,2042026.0,2042026.0,2042026.0,...,401.0,A00,369443.0,G01,CF01,EQADE-CHRG_GST,23.59,"23,59",G01,369443.0
4,ENCADE,12630.0,369443.0,JRIRI,JRIRI,2092024.0,3042026.0,2042026.0,2042026.0,2042026.0,...,401.0,A00,369443.0,G01,CF01,EQADE-CHRG_GST_CP,23.59,"-23,59",G01,369443.0

In [3]:
# 1. Nettoyage de la colonne Solde
df['Solde'] = df['Solde'].astype(str).str.replace(',', '.').astype(float)

In [18]:
df.groupby(['Group1'])['Solde'].sum().round(2).reset_index()

       Group1  Solde
0      ENCADE   -0.0
1  ENCLIBCOMM   -0.0
2      ENCMRB    0.0
3         G01    0.0
4         G02   -0.0
5         G03    0.0
6         G04   -0.0
7         G05   -0.0
8         G07    0.0

In [8]:
# Avec Pandas
resultat = df.groupby(['Group1', 'CritereCompte'])['Solde'].sum().round(2).reset_index()

In [19]:
resultat.head(30)

        Group1        CritereCompte       Solde
0       ENCADE  ENCADE-PRIME_TTC_CP -1916647.93
1       ENCADE      ENCADETTLBANQUE  1916647.93
2   ENCLIBCOMM      ENC-LIB_COMM_HT   269526.46
3   ENCLIBCOMM    ENC-LIB_COMM_TAXE    26951.64
4   ENCLIBCOMM     ENC-LIB_COMM_TTC  -296478.10
5       ENCMRB      EN-ECARTNEGATIF        0.01
6       ENCMRB       EN-GRANDECARTN        0.56
7       ENCMRB  ENCMRB-PRIME_TTC_CP  -292774.18
8       ENCMRB      ENCMRBTTLBANQUE   292773.61
9          G01       EQADE-CHRG_GST   519933.76
10         G01    EQADE-CHRG_GST_CP  -519933.76
11         G01       EQADE-COMM_TTC   258603.04
12         G01    EQADE-COMM_TTC_CP  -258603.04
13         G01       EQADE-PRIME_HT -1742409.90
14         G01      EQADE-PRIME_TTC  1916647.93
15         G01       EQADE-TAXE_TSA  -174238.03
16         G02      EQ-ECARTNEGATIF        0.23
17         G02      EQ-ECARTPOSITIF       -0.05
18         G02       EQ-GRANDECARTN      193.74
19         G02       EQMRB-CHRG_GST   -17637.99
20         G02    EQMRB-CHRG_GST_CP    17637.99
21         G02       EQMRB-COMM_TTC    -8818.95
22         G02    EQMRB-COMM_TTC_CP     8818.95
23         G02       EQMRB-PRIME_HT   -58792.86
24         G02      EQMRB-PRIME_TTC    67712.10
25         G02  EQMRB-TAXE_PARAFISC     -882.16
26         G02       EQMRB-TAXE_TSA    -8231.00
27         G03      EQ-ECARTNEGATIF        0.26
28         G03      EQ-ECARTPOSITIF       -0.21
29         G03       EQ-GRANDECARTN      543.47